<a href="https://colab.research.google.com/github/Monicarys/Auditorias/blob/main/Materializacion_automatizacion.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#**Información sobre la Revisión Trimestral**

##En este colab se quiere obtener un análisis de varias entidades fiscalizables. En donde sobresalgan los siguientes puntos:##

1. Análisis trimestral \\
  1.1 Cumplimiento e incumplimiento trimestral general

2. Análisis  por Módulo \\
  2.1 Cumplimiento e incumplimiento trimestral por Módulo 

3. ¿A qué corresponden los incumplimientos?

  3.1 Archivos de incumplimiento entidad-modulo \\
  3.2 Archivos de incumplimiento entides-modulo \\
  3.3 Archivos de incumplimiento entidades-modulos \\

4. Análisis mensual \\

  4.1 Análisis mensual por módulo \\
  4.2 Análisis mensual de los modulos de varias entidades fiscalizables \\
  4.3 Análisis general por mes de varias entidades \\
  
___

Las plantillas con las que se hará el análisis son las siguientes:

In [1]:
import pandas as pd
import numpy as np
import os
#Muestra los archivos
archivos=[file for file in os.listdir() if ".xlsm" in file]
archivos

['D_AlmoloyadeJuárez.xlsm', 'D_Ocoyoacac.xlsm', 'M_Ocoyoacac.xlsm']

In [2]:
#FUNCIONES GENERALES
#Funcion para exportar archivos

def exportar_excel(df, nombre):
  nombre_archivo=nombre+'.xlsm'
  return df.to_excel(nombre_archivo)


#Definimos la funcion que nos cuenta los SI's
def contar_si(X):
  return (X=='si').sum().sum()+(X=='SI').sum().sum()+(X=='Si').sum().sum()+(X=='sI').sum().sum()+(X=='Sí').sum().sum()
#Definimos la funcion que nos cuenta los NO's
def contar_no(X):
  return (X=='no').sum().sum()+(X=='NO').sum().sum()+(X=='No').sum().sum()+(X=='nO').sum().sum()
#Funcion para calcular el porcentaje

def contar_si_no(X):
  return contar_si(X)+contar_no(X)

def porcentaje_si(X):
  return round((contar_si(X)/contar_si_no(X))*100,2)

def porcentaje_no(X):
  return round((contar_no(X)/contar_si_no(X))*100,2)


#Definimos la funcion de leer y limpiar archivo
def leer_limpiar(archivo):
  df=pd.read_excel(archivo)
#Para quitar los Nan ocupamos la siguiente funcion
  df.fillna('', inplace=True)
#Intentando quitar \n, pero aun no sale
  return df

In [3]:
#FUNCIONES CREADORAS DE MODULOS
#Funcion para crear modulos (DEPENDE DE DF)
def crear_M1(df):
  M1=df.iloc[10:49, [1,2,3,6,7,8,9,10,11,12,13,14]] 
  M1.rename(columns={'Unnamed: 1':'Submodulo', 'Unnamed: 2':'N','Unnamed: 3':'Concepto', 'Unnamed: 6':'PDF Oct', 'Unnamed: 7':'XLS Oct','Unnamed: 8':'XML o TXT Oct', 'Unnamed: 9':'PDF Nov', 'Unnamed: 10':'XLS Nov','Unnamed: 11':'XML o TXT Nov', 'Unnamed: 12':'PDF Dic', 'Unnamed: 13':'XLS Dic','Unnamed: 14':'XML o TXT Dic'}, inplace=True)
  return M1

def crear_M2(df):
  M2=df.iloc[57:81, [1,2,3,6,7,8,9,10,11,12,13,14]]
  M2.rename(columns={'Unnamed: 1':'Submodulo', 'Unnamed: 2':'N','Unnamed: 3':'Concepto', 'Unnamed: 6':'PDF Oct', 'Unnamed: 7':'TXT Oct','Unnamed: 8':'Oct', 'Unnamed: 9':' PDF Nov', 'Unnamed: 10':'TXT Nov','Unnamed: 11':'Nov', 'Unnamed: 12':'PDF Dic', 'Unnamed: 13':'TXT Dic','Unnamed: 14':'Dic'}, inplace=True)
  return M2

def crear_M3(df):
  M3=df.iloc[88:98, [1,2,3,6,7,8,9,10,11,12,13,14]]
  M3.rename(columns={'Unnamed: 1':'Submodulo', 'Unnamed: 2':'N','Unnamed: 3':'Concepto', 'Unnamed: 6':'6Octu', 'Unnamed: 7':'7Oct','Unnamed: 8':'8Oct', 'Unnamed: 9':' 9Nov', 'Unnamed: 10':'10Nov','Unnamed: 11':'11Nov', 'Unnamed: 12':'PDF Dic', 'Unnamed: 13':'TXT Dic','Unnamed: 14':'14Dic'}, inplace=True)
  return M3

def crear_M4(df):
  M4=df.iloc[105:128, [1,2,3,6,7,8,9,10,11,12,13,14]]
  M4.rename(columns={'Unnamed: 1':'Submodulo', 'Unnamed: 2':'N','Unnamed: 3':'Concepto', 'Unnamed: 6':'PDF Oct', 'Unnamed: 7':'XLS Oct','Unnamed: 8':'TXT Oct', 'Unnamed: 9':'PDF Nov', 'Unnamed: 10':'XLS Nov','Unnamed: 11':'TXT Nov', 'Unnamed: 12':'PDF Dic', 'Unnamed: 13':'XLS Dic','Unnamed: 14':'TXT Dic'}, inplace=True)
  return M4

#Funciones para crear modulos mensuales(DEPENDE DEL DF)

def crear_M1_oct(df):
  M1=df.iloc[10:49, [1,2,3,6,7,8]] 
  M1.rename(columns={'Unnamed: 1':'Submodulo', 'Unnamed: 2':'N','Unnamed: 3':'Concepto', 'Unnamed: 6':'PDF Oct', 'Unnamed: 7':'XLS Oct','Unnamed: 8':'XML o TXT Oct', 'Unnamed: 9':'PDF Nov', 'Unnamed: 10':'XLS Nov','Unnamed: 11':'XML o TXT Nov', 'Unnamed: 12':'PDF Dic', 'Unnamed: 13':'XLS Dic','Unnamed: 14':'XML o TXT Dic'}, inplace=True)
  return M1
def crear_M2_oct(df):
  M2=df.iloc[57:81, [1,2,3,6,7,8]] 
  M2.rename(columns={'Unnamed: 1':'Submodulo', 'Unnamed: 2':'N','Unnamed: 3':'Concepto', 'Unnamed: 6':'PDF Oct', 'Unnamed: 7':'XLS Oct','Unnamed: 8':'XML o TXT Oct', 'Unnamed: 9':'PDF Nov', 'Unnamed: 10':'XLS Nov','Unnamed: 11':'XML o TXT Nov', 'Unnamed: 12':'PDF Dic', 'Unnamed: 13':'XLS Dic','Unnamed: 14':'XML o TXT Dic'}, inplace=True)
  return M2
def crear_M3_oct(df):
  M3=df.iloc[88:98, [1,2,3,6,7,8]] 
  M3.rename(columns={'Unnamed: 1':'Submodulo', 'Unnamed: 2':'N','Unnamed: 3':'Concepto', 'Unnamed: 6':'PDF Oct', 'Unnamed: 7':'XLS Oct','Unnamed: 8':'XML o TXT Oct', 'Unnamed: 9':'PDF Nov', 'Unnamed: 10':'XLS Nov','Unnamed: 11':'XML o TXT Nov', 'Unnamed: 12':'PDF Dic', 'Unnamed: 13':'XLS Dic','Unnamed: 14':'XML o TXT Dic'}, inplace=True)
  return M3
def crear_M4_oct(df):
  M4=df.iloc[105:128, [1,2,3,6,7,8]] 
  M4.rename(columns={'Unnamed: 1':'Submodulo', 'Unnamed: 2':'N','Unnamed: 3':'Concepto', 'Unnamed: 6':'PDF Oct', 'Unnamed: 7':'XLS Oct','Unnamed: 8':'XML o TXT Oct', 'Unnamed: 9':'PDF Nov', 'Unnamed: 10':'XLS Nov','Unnamed: 11':'XML o TXT Nov', 'Unnamed: 12':'PDF Dic', 'Unnamed: 13':'XLS Dic','Unnamed: 14':'XML o TXT Dic'}, inplace=True)
  return M4

def crear_M1_nov(df):
  M1=df.iloc[10:49, [1,2,3,9,10,11]] 
  M1.rename(columns={'Unnamed: 1':'Submodulo', 'Unnamed: 2':'N','Unnamed: 3':'Concepto', 'Unnamed: 6':'PDF Oct', 'Unnamed: 7':'XLS Oct','Unnamed: 8':'XML o TXT Oct', 'Unnamed: 9':'PDF Nov', 'Unnamed: 10':'XLS Nov','Unnamed: 11':'XML o TXT Nov', 'Unnamed: 12':'PDF Dic', 'Unnamed: 13':'XLS Dic','Unnamed: 14':'XML o TXT Dic'}, inplace=True)
  return M1
def crear_M2_nov(df):
  M2=df.iloc[57:81, [1,2,3,9,10,11]] 
  M2.rename(columns={'Unnamed: 1':'Submodulo', 'Unnamed: 2':'N','Unnamed: 3':'Concepto', 'Unnamed: 6':'PDF Oct', 'Unnamed: 7':'XLS Oct','Unnamed: 8':'XML o TXT Oct', 'Unnamed: 9':'PDF Nov', 'Unnamed: 10':'XLS Nov','Unnamed: 11':'XML o TXT Nov', 'Unnamed: 12':'PDF Dic', 'Unnamed: 13':'XLS Dic','Unnamed: 14':'XML o TXT Dic'}, inplace=True)
  return M2
def crear_M3_nov(df):
  M3=df.iloc[88:98, [1,2,3,9,10,11]] 
  M3.rename(columns={'Unnamed: 1':'Submodulo', 'Unnamed: 2':'N','Unnamed: 3':'Concepto', 'Unnamed: 6':'PDF Oct', 'Unnamed: 7':'XLS Oct','Unnamed: 8':'XML o TXT Oct', 'Unnamed: 9':'PDF Nov', 'Unnamed: 10':'XLS Nov','Unnamed: 11':'XML o TXT Nov', 'Unnamed: 12':'PDF Dic', 'Unnamed: 13':'XLS Dic','Unnamed: 14':'XML o TXT Dic'}, inplace=True)
  return M3
def crear_M4_nov(df):
  M4=df.iloc[105:128, [1,2,3,9,10,11]] 
  M4.rename(columns={'Unnamed: 1':'Submodulo', 'Unnamed: 2':'N','Unnamed: 3':'Concepto', 'Unnamed: 6':'PDF Oct', 'Unnamed: 7':'XLS Oct','Unnamed: 8':'XML o TXT Oct', 'Unnamed: 9':'PDF Nov', 'Unnamed: 10':'XLS Nov','Unnamed: 11':'XML o TXT Nov', 'Unnamed: 12':'PDF Dic', 'Unnamed: 13':'XLS Dic','Unnamed: 14':'XML o TXT Dic'}, inplace=True)
  return M4

def crear_M1_dic(df):
  M1=df.iloc[10:49, [1,2,3,12,13,14]] 
  M1.rename(columns={'Unnamed: 1':'Submodulo', 'Unnamed: 2':'N','Unnamed: 3':'Concepto', 'Unnamed: 6':'PDF Oct', 'Unnamed: 7':'XLS Oct','Unnamed: 8':'XML o TXT Oct', 'Unnamed: 9':'PDF Nov', 'Unnamed: 10':'XLS Nov','Unnamed: 11':'XML o TXT Nov', 'Unnamed: 12':'PDF Dic', 'Unnamed: 13':'XLS Dic','Unnamed: 14':'XML o TXT Dic'}, inplace=True)
  return M1
def crear_M2_dic(df):
  M2=df.iloc[57:81, [1,2,3,12,13,14]] 
  M2.rename(columns={'Unnamed: 1':'Submodulo', 'Unnamed: 2':'N','Unnamed: 3':'Concepto', 'Unnamed: 6':'PDF Oct', 'Unnamed: 7':'XLS Oct','Unnamed: 8':'XML o TXT Oct', 'Unnamed: 9':'PDF Nov', 'Unnamed: 10':'XLS Nov','Unnamed: 11':'XML o TXT Nov', 'Unnamed: 12':'PDF Dic', 'Unnamed: 13':'XLS Dic','Unnamed: 14':'XML o TXT Dic'}, inplace=True)
  return M2
def crear_M3_dic(df):
  M3=df.iloc[88:98, [1,2,3,12,13,14]] 
  M3.rename(columns={'Unnamed: 1':'Submodulo', 'Unnamed: 2':'N','Unnamed: 3':'Concepto', 'Unnamed: 6':'PDF Oct', 'Unnamed: 7':'XLS Oct','Unnamed: 8':'XML o TXT Oct', 'Unnamed: 9':'PDF Nov', 'Unnamed: 10':'XLS Nov','Unnamed: 11':'XML o TXT Nov', 'Unnamed: 12':'PDF Dic', 'Unnamed: 13':'XLS Dic','Unnamed: 14':'XML o TXT Dic'}, inplace=True)
  return M3
def crear_M4_dic(df):
  M4=df.iloc[105:128, [1,2,3,12,13,14]] 
  M4.rename(columns={'Unnamed: 1':'Submodulo', 'Unnamed: 2':'N','Unnamed: 3':'Concepto', 'Unnamed: 6':'PDF Oct', 'Unnamed: 7':'XLS Oct','Unnamed: 8':'XML o TXT Oct', 'Unnamed: 9':'PDF Nov', 'Unnamed: 10':'XLS Nov','Unnamed: 11':'XML o TXT Nov', 'Unnamed: 12':'PDF Dic', 'Unnamed: 13':'XLS Dic','Unnamed: 14':'XML o TXT Dic'}, inplace=True)
  return M4



#Funcion para crear MODULO y MODULOS MENSUALES que depende del ARCHIVO y el MODULO o MODULO MENSUAL
def crear_modulo(archivo, modulo):
  df=leer_limpiar(archivo)

  if modulo=='M1':
    M1=df.iloc[10:49, [1,2,3,6,7,8,9,10,11,12,13,14]] 
    M1.rename(columns={'Unnamed: 1':'Submodulo', 'Unnamed: 2':'N','Unnamed: 3':'Concepto', 'Unnamed: 6':'PDF Oct', 'Unnamed: 7':'XLS Oct','Unnamed: 8':'XML o TXT Oct', 'Unnamed: 9':'PDF Nov', 'Unnamed: 10':'XLS Nov','Unnamed: 11':'XML o TXT Nov', 'Unnamed: 12':'PDF Dic', 'Unnamed: 13':'XLS Dic','Unnamed: 14':'XML o TXT Dic'}, inplace=True)
    return M1

  if modulo=='M1_oct':
    M_oct=df.iloc[10:49, [1,2,3,6,7,8]] 
    M_oct.rename(columns={'Unnamed: 1':'Submodulo', 'Unnamed: 2':'N','Unnamed: 3':'Concepto', 'Unnamed: 6':'PDF Oct', 'Unnamed: 7':'XLS Oct','Unnamed: 8':'XML o TXT Oct'}, inplace=True)
    return M_oct

  if modulo=='M1_nov':
    M1_nov=df.iloc[10:49, [1,2,3,9,10,11]] 
    M1_nov.rename(columns={'Unnamed: 1':'Submodulo', 'Unnamed: 2':'N','Unnamed: 3':'Concepto', 'Unnamed: 6':'PDF Oct', 'Unnamed: 7':'XLS Oct','Unnamed: 8':'XML o TXT Oct', 'Unnamed: 9':'PDF Nov', 'Unnamed: 10':'XLS Nov','Unnamed: 11':'XML o TXT Nov'}, inplace=True)
    return M1_nov

  if modulo=='M1_dic':
    M1_dic=df.iloc[10:49, [1,2,3,12,13,14]] 
    M1_dic.rename(columns={'Unnamed: 1':'Submodulo', 'Unnamed: 2':'N','Unnamed: 3':'Concepto', 'Unnamed: 12':'PDF Dic', 'Unnamed: 13':'XLS Dic','Unnamed: 14':'XML o TXT Dic'}, inplace=True)
    return M1_dic

  if modulo=='M2':
    M2=df.iloc[57:81, [1,2,3,6,7,8,9,10,11,12,13,14]]
    M2.rename(columns={'Unnamed: 1':'Submodulo', 'Unnamed: 2':'N','Unnamed: 3':'Concepto', 'Unnamed: 6':'PDF Oct', 'Unnamed: 7':'TXT Oct','Unnamed: 8':'Oct', 'Unnamed: 9':' PDF Nov', 'Unnamed: 10':'TXT Nov','Unnamed: 11':'Nov', 'Unnamed: 12':'PDF Dic', 'Unnamed: 13':'TXT Dic','Unnamed: 14':'Dic'}, inplace=True)
    return M2
  if modulo=='M2_oct':
    M2_oct=df.iloc[57:81, [1,2,3,6,7,8]]
    M2_oct.rename(columns={'Unnamed: 1':'Submodulo', 'Unnamed: 2':'N','Unnamed: 3':'Concepto', 'Unnamed: 6':'PDF Oct', 'Unnamed: 7':'TXT Oct','Unnamed: 8':'Oct', 'Unnamed: 9':' PDF Nov', 'Unnamed: 10':'TXT Nov','Unnamed: 11':'Nov', 'Unnamed: 12':'PDF Dic', 'Unnamed: 13':'TXT Dic','Unnamed: 14':'Dic'}, inplace=True)
    return M2_oct
  if modulo=='M2_nov':
    M2_nov=df.iloc[57:81, [1,2,3,9,10,11]]
    M2_nov.rename(columns={'Unnamed: 1':'Submodulo', 'Unnamed: 2':'N','Unnamed: 3':'Concepto', 'Unnamed: 6':'PDF Oct', 'Unnamed: 7':'TXT Oct','Unnamed: 8':'Oct', 'Unnamed: 9':' PDF Nov', 'Unnamed: 10':'TXT Nov','Unnamed: 11':'Nov', 'Unnamed: 12':'PDF Dic', 'Unnamed: 13':'TXT Dic','Unnamed: 14':'Dic'}, inplace=True)
    return M2_nov
  if modulo=='M2_dic':
    M2_dic=df.iloc[57:81, [1,2,3,12,13,14]]
    M2_dic.rename(columns={'Unnamed: 1':'Submodulo', 'Unnamed: 2':'N','Unnamed: 3':'Concepto','Unnamed: 12':'PDF Dic', 'Unnamed: 13':'TXT Dic','Unnamed: 14':'Dic'}, inplace=True)
    return M2_dic

  if modulo=='M3':
    M3=df.iloc[88:98, [1,2,3,6,7,8,9,10,11,12,13,14]]
    M3.rename(columns={'Unnamed: 1':'Submodulo', 'Unnamed: 2':'N','Unnamed: 3':'Concepto', 'Unnamed: 6':'6Octu', 'Unnamed: 7':'7Oct','Unnamed: 8':'8Oct', 'Unnamed: 9':' 9Nov', 'Unnamed: 10':'10Nov','Unnamed: 11':'11Nov', 'Unnamed: 12':'PDF Dic', 'Unnamed: 13':'TXT Dic','Unnamed: 14':'14Dic'}, inplace=True)
    return M3

  if modulo=='M3_oct':
    M3_oct=df.iloc[88:98, [1,2,3,6,7,8]]
    M3_oct.rename(columns={'Unnamed: 1':'Submodulo', 'Unnamed: 2':'N','Unnamed: 3':'Concepto', 'Unnamed: 6':'6Octu', 'Unnamed: 7':'7Oct','Unnamed: 8':'8Oct', 'Unnamed: 9':' 9Nov', 'Unnamed: 10':'10Nov','Unnamed: 11':'11Nov', 'Unnamed: 12':'PDF Dic', 'Unnamed: 13':'TXT Dic','Unnamed: 14':'14Dic'}, inplace=True)
    return M3_oct

  if modulo=='M3_nov':
    M3_nov=df.iloc[88:98, [1,2,3,9,10,11]]
    M3_nov.rename(columns={'Unnamed: 1':'Submodulo', 'Unnamed: 2':'N','Unnamed: 3':'Concepto', 'Unnamed: 6':'6Octu', 'Unnamed: 7':'7Oct','Unnamed: 8':'8Oct', 'Unnamed: 9':' 9Nov', 'Unnamed: 10':'10Nov','Unnamed: 11':'11Nov', 'Unnamed: 12':'PDF Dic', 'Unnamed: 13':'TXT Dic','Unnamed: 14':'14Dic'}, inplace=True)
    return M3_nov
  if modulo=='M3_dic':
    M3_dic=df.iloc[88:98, [1,2,3,12,13,14]]
    M3_dic.rename(columns={'Unnamed: 1':'Submodulo', 'Unnamed: 2':'N','Unnamed: 3':'Concepto', 'Unnamed: 6':'6Octu', 'Unnamed: 7':'7Oct','Unnamed: 8':'8Oct', 'Unnamed: 9':' 9Nov', 'Unnamed: 10':'10Nov','Unnamed: 11':'11Nov', 'Unnamed: 12':'PDF Dic', 'Unnamed: 13':'TXT Dic','Unnamed: 14':'14Dic'}, inplace=True)
    return M3_dic


  if modulo=='M4':
    M4=df.iloc[105:128, [1,2,3,6,7,8,9,10,11,12,13,14]]
    M4.rename(columns={'Unnamed: 1':'Submodulo', 'Unnamed: 2':'N','Unnamed: 3':'Concepto', 'Unnamed: 6':'PDF Oct', 'Unnamed: 7':'XLS Oct','Unnamed: 8':'TXT Oct', 'Unnamed: 9':'PDF Nov', 'Unnamed: 10':'XLS Nov','Unnamed: 11':'TXT Nov', 'Unnamed: 12':'PDF Dic', 'Unnamed: 13':'XLS Dic','Unnamed: 14':'TXT Dic'}, inplace=True)
    return M4

  if modulo=='M4_oct':
    M4_oct=df.iloc[105:128, [1,2,3,6,7,8]]
    M4_oct.rename(columns={'Unnamed: 1':'Submodulo', 'Unnamed: 2':'N','Unnamed: 3':'Concepto', 'Unnamed: 6':'PDF Oct', 'Unnamed: 7':'XLS Oct','Unnamed: 8':'TXT Oct', 'Unnamed: 9':'PDF Nov', 'Unnamed: 10':'XLS Nov','Unnamed: 11':'TXT Nov', 'Unnamed: 12':'PDF Dic', 'Unnamed: 13':'XLS Dic','Unnamed: 14':'TXT Dic'}, inplace=True)
    return M4_oct
  if modulo=='M4_nov':
    M4_nov=df.iloc[105:128, [1,2,3,9,10,11]]
    M4_nov.rename(columns={'Unnamed: 1':'Submodulo', 'Unnamed: 2':'N','Unnamed: 3':'Concepto', 'Unnamed: 6':'PDF Oct', 'Unnamed: 7':'XLS Oct','Unnamed: 8':'TXT Oct', 'Unnamed: 9':'PDF Nov', 'Unnamed: 10':'XLS Nov','Unnamed: 11':'TXT Nov', 'Unnamed: 12':'PDF Dic', 'Unnamed: 13':'XLS Dic','Unnamed: 14':'TXT Dic'}, inplace=True)
    return M4_nov
  if modulo=='M4_dic':
    M4_dic=df.iloc[105:128, [1,2,3,12,13,14]]
    M4_dic.rename(columns={'Unnamed: 1':'Submodulo', 'Unnamed: 2':'N','Unnamed: 3':'Concepto', 'Unnamed: 6':'PDF Oct', 'Unnamed: 7':'XLS Oct','Unnamed: 8':'TXT Oct', 'Unnamed: 9':'PDF Nov', 'Unnamed: 10':'XLS Nov','Unnamed: 11':'TXT Nov', 'Unnamed: 12':'PDF Dic', 'Unnamed: 13':'XLS Dic','Unnamed: 14':'TXT Dic'}, inplace=True)
    return M4_dic

In [4]:
#Funciones para obtener el nombre y tipo de entidad
def nombre_entidad(archivo):
  return (str(archivo)[:-5])[2:]

def tipo_entidad(archivo):
  inicial=str(archivo)[:2]
  if inicial=='D_':
    return 'DIF'
  if inicial=='I_':
    return'IMCUFIDE'
  if inicial=='IM':
    return 'IMJUVE'
  if inicial=='O_':
    return 'ODAS'
  if inicial=='M_':
    return 'MUNICIPIO'
  #print("Error en el archivo", archivo)
  #raise ValueError

In [5]:

#Funcion para encontrar la dataframe filtrada en la que aparecen los no
#Depende del archivo y el modulo Y LA FUNCION crear_modulo

def filtro_no_modulo(archivo, modulo):
  M = crear_modulo(archivo, modulo)
  if modulo=='M1':
    mask_M=(M[['PDF Oct','XLS Oct','XML o TXT Oct', 'PDF Nov', 'XLS Nov','XML o TXT Nov','PDF Dic','XLS Dic','XML o TXT Dic']] ==('No'or 'no' or 'NO' or 'nO')).any(axis=1)
    return M[mask_M]
  if modulo=='M2':
    mask_M=(M[['PDF Oct','TXT Oct','Oct',' PDF Nov','TXT Nov','Nov','PDF Dic', 'TXT Dic','Dic']] ==('No'or 'no'or 'NO'or 'nO')).any(axis=1)
    return M[mask_M]
  if modulo=='M3':
    mask_M=(M[['6Octu','7Oct','8Oct',' 9Nov','10Nov','11Nov','PDF Dic','TXT Dic','14Dic']] ==('No'or 'no'or 'NO'or 'nO')).any(axis=1)
    return M[mask_M]
  if modulo=='M4':
    mask_M=(M[['PDF Oct', 'XLS Oct','TXT Oct','PDF Nov','XLS Nov','TXT Nov','PDF Dic', 'XLS Dic','TXT Dic']] ==('No'or 'no'or 'NO'or 'nO')).any(axis=1)
    return M[mask_M]

#Funcion que nos devuelve la tabla de los incumplimientos del Modulo X de un archivo, depende de las DOS FUNCIONES ANTERIORES
def archivos_incumplimiento_modulo_entidad(archivo,modulo):
  M = crear_modulo(archivo, modulo)
  filtered_M_no = filtro_no_modulo(archivo,modulo)
#Para esto creemos una lista de los nombres de las columnas
  columnas=filtered_M_no.columns.tolist()
#Creemos una lista de los nombres de las filas
  filas=filtered_M_no.index.tolist()
  my_columns=['Entidad', 'Tipo', 'Modulo', 'Concepto', 'Archivo al que corresponde']
#definimos nuestra primer fila como vacia 
  my_data = np.array([['','','','','']])
  for i in filas:
    for j in columnas:
      if filtered_M_no.loc[i,j]=='No':
        lo_de_medio= np.array([[nombre_entidad(archivo),
                           tipo_entidad(archivo),
                           modulo,
                           filtered_M_no.loc[i,'Concepto'],
                           j       
                           ]])
        my_data=np.append (my_data, lo_de_medio, axis = 0)

  my_dataframe = pd.DataFrame(data=my_data, columns=my_columns)
  my_dataframe= my_dataframe.drop([0],axis=0)
  return my_dataframe


#Funcion que nos devuelve la tabla de los incumplimientos del Modulo X de todos los archivos
def archivos_incumplimiento_modulo_entidades(archivos, modulo):
  #Definimos la lista de los archivos de incumplimiento de cada archivo
  AIM1=[archivos_incumplimiento_modulo_entidad(archivo,modulo) for archivo in archivos]
  #Concatenamos verticalmente en una sola dataframe
  vertical_stack = pd.concat(AIM1, axis=0)
  return vertical_stack

In [6]:
def analisis_general(archivos):


  #Creamos nuestras columnas
  columnas_ct=['Entidad', 'Tipo', 'Total de no', 'Total de si', 'Pocentaje de incumplimiento Trimestral','Pocentaje de cumplimiento Trimestral']
  #definimos nuestra primer fila como vacia 
  my_data_ct = np.array([['','','','','','' ]])

  for archivo in archivos:
    df=leer_limpiar(archivo)
    #Creamos nuestros modulos
    M1=crear_M1(df)
    M2=crear_M2(df)
    M3=crear_M3(df)
    M4=crear_M4(df)

  
    #Definimos algunas variables que ocuparemos
    sis_trimestre=contar_si(M1)+contar_si(M2)+contar_si(M3)+contar_si(M4)
    nos_trimestre=contar_no(M1)+contar_no(M2)+contar_no(M3)+contar_no(M4)
    siyno_trimestre=sis_trimestre + nos_trimestre
    porcentaje_si_trimestre=round((sis_trimestre/(siyno_trimestre)*100),2)
    porcentaje_no_trimestre=round((nos_trimestre/(siyno_trimestre)*100),2)

    #Vamos agregando cada fila con la informacion de cada modulo
    my_data_ct=np.append (my_data_ct, np.array([[nombre_entidad(archivo),
                           tipo_entidad(archivo), nos_trimestre, sis_trimestre, porcentaje_no_trimestre, porcentaje_si_trimestre]]), axis = 0)


  #Hacemos nuestro dataframe con tan informacion
  df_ct = pd.DataFrame(data=my_data_ct, columns=columnas_ct)
  return df_ct

#**1. Análisis trimestral**

**1.1 Cumplimiento e incumplimiento trimestral general**

Este es el análisis mas general que se puede obtener, contabiliza el total de Sis y el total de Nos de toda la revision de las entidades fiscalizable

In [7]:
analisis_general(archivos)

/usr/local/lib/python3.7/dist-packages/openpyxl/worksheet/_reader.py:312: UserWarning: Data Validation extension is not supported and will be removed
  warn(msg)

,Entidad,Tipo,Total de no,Total de si,Pocentaje de incumplimiento Trimestral,Pocentaje de cumplimiento Trimestral
0,,,,,,
1,AlmoloyadeJuárez,DIF,105,152,40.86,59.14
2,Ocoyoacac,DIF,43,217,16.54,83.46
3,Ocoyoacac,MUNICIPIO,110,147,42.8,57.2

In [8]:
#Exportar a un excel 
exportar_excel(analisis_general(archivos), 'analisis_general_entidades')

/usr/local/lib/python3.7/dist-packages/openpyxl/worksheet/_reader.py:312: UserWarning: Data Validation extension is not supported and will be removed
  warn(msg)

Tambien se puede obtener de una entidad fiscalizable en particular

In [9]:
analisis_general([archivos[1]])

/usr/local/lib/python3.7/dist-packages/openpyxl/worksheet/_reader.py:312: UserWarning: Data Validation extension is not supported and will be removed
  warn(msg)

,Entidad,Tipo,Total de no,Total de si,Pocentaje de incumplimiento Trimestral,Pocentaje de cumplimiento Trimestral
0,,,,,,
1,Ocoyoacac,DIF,43,217,16.54,83.46

#**2. Análisis por modulo de las entidades fiscalizables**

**2.1 Cumplimiento e incumplimiento un modulo**

El cumplimiento de un modulo en particular de las entidades fiscalizables se puede calcular utilizando la siguiente funcion

In [10]:
#Hacemos nuestro dataframe con tal informacion

def analisis_modulo(archivos,modulo):

  #Creamos nuestras columnas
  columnas_cM=['Entidad', 'Tipo', 'Módulo' , 'Total de no','Total de si', 'Pocentaje de incumplimiento', 'Pocentaje de cumplimiento']
  #definimos nuestra primer fila como vacia 
  my_data_cM = np.array([['','','','','','','' ]])

  for archivo in archivos:
    M=crear_modulo(archivo, modulo)

  #Vamos agregando cada fila con la informacion de cada modulo
    my_data_cM=np.append (my_data_cM, np.array([[nombre_entidad(archivo),
                         tipo_entidad(archivo), modulo,contar_no(M), contar_si(M), porcentaje_no(M),porcentaje_si(M) ]]), axis = 0)
  
  df_cM = pd.DataFrame(data=my_data_cM, columns=columnas_cM)
  df_cM= df_cM.drop([0],axis=0)
  
  return df_cM

In [11]:
analisis_modulo(archivos, 'M2')

/usr/local/lib/python3.7/dist-packages/openpyxl/worksheet/_reader.py:312: UserWarning: Data Validation extension is not supported and will be removed
  warn(msg)

,Entidad,Tipo,Módulo,Total de no,Total de si,Pocentaje de incumplimiento,Pocentaje de cumplimiento
1,AlmoloyadeJuárez,DIF,M2,0,53,0.0,100.0
2,Ocoyoacac,DIF,M2,4,49,7.55,92.45
3,Ocoyoacac,MUNICIPIO,M2,14,36,28.0,72.0

**2.1 Cumplimiento e incumplimiento de varios modulos**

El cumplimiento e incumplimiento de varios modulos de las entidades fiscalizables se puede calcular utilizando la siguiente funcion

In [12]:
#Funcion que nos devuelve el analisis de todos los modulos de las entidades fiscalizables
def analisis_modulos(archivos, modulos):
  #Definimos la lista de los archivos de incumplimiento de cada archivo
  AM=[analisis_modulo(archivos,modulo) for modulo in modulos]
  #Concatenamos verticalmente en una sola dataframe
  vertical_stack = pd.concat(AM, axis=0)
  return vertical_stack

In [13]:
analisis_modulos(archivos,['M1','M2','M3','M4'])

/usr/local/lib/python3.7/dist-packages/openpyxl/worksheet/_reader.py:312: UserWarning: Data Validation extension is not supported and will be removed
  warn(msg)

,Entidad,Tipo,Módulo,Total de no,Total de si,Pocentaje de incumplimiento,Pocentaje de cumplimiento
1,AlmoloyadeJuárez,DIF,M1,42,85,33.07,66.93
2,Ocoyoacac,DIF,M1,15,115,11.54,88.46
3,Ocoyoacac,MUNICIPIO,M1,53,77,40.77,59.23
1,AlmoloyadeJuárez,DIF,M2,0,53,0.0,100.0
2,Ocoyoacac,DIF,M2,4,49,7.55,92.45
3,Ocoyoacac,MUNICIPIO,M2,14,36,28.0,72.0
1,AlmoloyadeJuárez,DIF,M3,9,2,81.82,18.18
2,Ocoyoacac,DIF,M3,7,4,63.64,36.36
3,Ocoyoacac,MUNICIPIO,M3,9,2,81.82,18.18
1,AlmoloyadeJuárez,DIF,M4,54,12,81.82,18.18
2,Ocoyoacac,DIF,M4,17,49,25.76,74.24
3,Ocoyoacac,MUNICIPIO,M4,34,32,51.52,48.48

In [14]:
#Exportar a un excel 
exportar_excel(analisis_modulos(archivos,['M1','M2','M3','M4']), 'analisis_modulos_entidades')

/usr/local/lib/python3.7/dist-packages/openpyxl/worksheet/_reader.py:312: UserWarning: Data Validation extension is not supported and will be removed
  warn(msg)

#**3.¿A qué corresponde el incumplimiento de las entidades fiscalizables?**

**3.1 Archivos de incumplimiento entidad-modulo**

Existen varias maneras de analizar a que archivos corresponden los incumplimientos. Comezaremos desde lo particular e iremos a lo general

In [15]:
#Funcion para encontrar la dataframe filtrada en la que aparecen los no
#Depende del archivo y el modulo

def filtro_no_modulo(archivo, modulo):
  M = crear_modulo(archivo, modulo)
  if modulo=='M1':
    mask_M=(M[['PDF Oct','XLS Oct','XML o TXT Oct', 'PDF Nov', 'XLS Nov','XML o TXT Nov','PDF Dic','XLS Dic','XML o TXT Dic']] ==('No'or 'no' or 'NO' or 'nO')).any(axis=1)
    return M[mask_M]
  if modulo=='M2':
    mask_M=(M[['PDF Oct','TXT Oct','Oct',' PDF Nov','TXT Nov','Nov','PDF Dic', 'TXT Dic','Dic']] ==('No'or 'no'or 'NO'or 'nO')).any(axis=1)
    return M[mask_M]
  if modulo=='M3':
    mask_M=(M[['6Octu','7Oct','8Oct',' 9Nov','10Nov','11Nov','PDF Dic','TXT Dic','14Dic']] ==('No'or 'no'or 'NO'or 'nO')).any(axis=1)
    return M[mask_M]
  if modulo=='M4':
    mask_M=(M[['PDF Oct', 'XLS Oct','TXT Oct','PDF Nov','XLS Nov','TXT Nov','PDF Dic', 'XLS Dic','TXT Dic']] ==('No'or 'no'or 'NO'or 'nO')).any(axis=1)
    return M[mask_M]

def archivos_incumplimiento_modulo_entidad(archivo,modulo):
  M = crear_modulo(archivo, modulo)
  filtered_M_no = filtro_no_modulo(archivo,modulo)
#Para esto creemos una lista de los nombres de las columnas
  columnas=filtered_M_no.columns.tolist()
#Creemos una lista de los nombres de las filas
  filas=filtered_M_no.index.tolist()
  my_columns=['Entidad', 'Tipo', 'Modulo', 'Concepto', 'Archivo al que corresponde']
#definimos nuestra primer fila como vacia 
  my_data = np.array([['','','','','']])
  for i in filas:
    for j in columnas:
      if filtered_M_no.loc[i,j]=='No':
        lo_de_medio= np.array([[nombre_entidad(archivo),
                           tipo_entidad(archivo),
                           modulo,
                           filtered_M_no.loc[i,'Concepto'],
                           j       
                           ]])
        my_data=np.append (my_data, lo_de_medio, axis = 0)

  my_dataframe = pd.DataFrame(data=my_data, columns=my_columns)
  my_dataframe= my_dataframe.drop([0],axis=0)
  return my_dataframe

Con la siguiente funcion obtenemos los archivos de incumplimiento de una entidad fiscalizable y correspondientes a un modulo.

In [16]:
archivo=archivos[1]
archivos_incumplimiento_modulo_entidad(archivo,'M1')

/usr/local/lib/python3.7/dist-packages/openpyxl/worksheet/_reader.py:312: UserWarning: Data Validation extension is not supported and will be removed
  warn(msg)

,Entidad,Tipo,Modulo,Concepto,Archivo al que corresponde
1,Ocoyoacac,DIF,M1,Dictamen de Estados Financieros a,PDF Dic
2,Ocoyoacac,DIF,M1,Catálogo de Proveedores de Bienes y Servicios,PDF Dic
3,Ocoyoacac,DIF,M1,Catálogo de Proveedores de Bienes y Servicios,XLS Dic
4,Ocoyoacac,DIF,M1,Dictámenes de Adjudicación Emitidos por el Com...,PDF Dic
5,Ocoyoacac,DIF,M1,Dictámenes de Adjudicación Emitidos por el Com...,XLS Dic
6,Ocoyoacac,DIF,M1,Dictámenes de Adjudicación Emitidos por el Com...,PDF Dic
7,Ocoyoacac,DIF,M1,Dictámenes de Adjudicación Emitidos por el Com...,XLS Dic
8,Ocoyoacac,DIF,M1,Dictámenes de Adjudicación Emitidos por el Com...,PDF Dic
9,Ocoyoacac,DIF,M1,Dictámenes de Adjudicación Emitidos por el Com...,XLS Dic
10,Ocoyoacac,DIF,M1,Conciliación de Obra Pública c,PDF Oct
11,Ocoyoacac,DIF,M1,Conciliación de Obra Pública c,XLS Oct
12,Ocoyoacac,DIF,M1,Conciliación de Obra Pública c,PDF Nov
13,Ocoyoacac,DIF,M1,Conciliación de Obra Pública c,XLS Nov
14,Ocoyoacac,DIF,M1,Conciliación de Obra Pública c,PDF Dic
15,Ocoyoacac,DIF,M1,Conciliación de Obra Pública c,XLS Dic

**3.2 Archivos de incumplimiento entidades-módulo**

Con la siguiente función podemos analizar los archivos de incumplimiento por modulo de varias entidades fiscalizables

In [17]:
#Funcion que nos devuelve la tabla de los incumplimientos del Modulo 1 de todos los archivos
def archivos_incumplimiento_modulo_entidades(archivos, modulo):
  #Definimos la lista de los archivos de incumplimiento de cada archivo
  AIM1=[archivos_incumplimiento_modulo_entidad(archivo,modulo) for archivo in archivos]
  #Concatenamos verticalmente en una sola dataframe
  vertical_stack = pd.concat(AIM1, axis=0)
  return vertical_stack

In [18]:
archivos_incumplimiento_modulo_entidades(archivos,'M1')

/usr/local/lib/python3.7/dist-packages/openpyxl/worksheet/_reader.py:312: UserWarning: Data Validation extension is not supported and will be removed
  warn(msg)

,Entidad,Tipo,Modulo,Concepto,Archivo al que corresponde
1,AlmoloyadeJuárez,DIF,M1,Notas de Desglose,PDF Oct
2,AlmoloyadeJuárez,DIF,M1,Notas de Desglose,XLS Oct
3,AlmoloyadeJuárez,DIF,M1,Notas de Desglose,PDF Nov
4,AlmoloyadeJuárez,DIF,M1,Notas de Desglose,XLS Nov
5,AlmoloyadeJuárez,DIF,M1,Notas de Desglose,PDF Dic
...,...,...,...,...,...
49,Ocoyoacac,MUNICIPIO,M1,Conciliación de Obra Pública c,XLS Oct
50,Ocoyoacac,MUNICIPIO,M1,Conciliación de Obra Pública c,PDF Nov
51,Ocoyoacac,MUNICIPIO,M1,Conciliación de Obra Pública c,XLS Nov
52,Ocoyoacac,MUNICIPIO,M1,Conciliación de Obra Pública c,PDF Dic
53,Ocoyoacac,MUNICIPIO,M1,Conciliación de Obra Pública c,XLS Dic

**3.3 Archivos de incumplimiento entidades-modulos**

In [19]:
#Funcion que nos devuelve la tabla de los incumplimientos de los modulos de todos los archivos
def archivos_incumplimiento_modulos_entidades(archivos, modulos):
  #Definimos la lista de los archivos de incumplimiento de cada archivo
  AIM1=[archivos_incumplimiento_modulo_entidades(archivos,modulo) for modulo in modulos]
  #Concatenamos verticalmente en una sola dataframe
  vertical_stack = pd.concat(AIM1, axis=0)
  return vertical_stack

In [20]:
archivos_incumplimiento_modulos_entidades(archivos,['M1','M2','M3','M4'])

/usr/local/lib/python3.7/dist-packages/openpyxl/worksheet/_reader.py:312: UserWarning: Data Validation extension is not supported and will be removed
  warn(msg)

,Entidad,Tipo,Modulo,Concepto,Archivo al que corresponde
1,AlmoloyadeJuárez,DIF,M1,Notas de Desglose,PDF Oct
2,AlmoloyadeJuárez,DIF,M1,Notas de Desglose,XLS Oct
3,AlmoloyadeJuárez,DIF,M1,Notas de Desglose,PDF Nov
4,AlmoloyadeJuárez,DIF,M1,Notas de Desglose,XLS Nov
5,AlmoloyadeJuárez,DIF,M1,Notas de Desglose,PDF Dic
...,...,...,...,...,...
30,Ocoyoacac,MUNICIPIO,M4,Hoja de Trabajo para la Conciliación Físico Co...,XLS Dic
31,Ocoyoacac,MUNICIPIO,M4,Conciliación Físico-Contable de Bienes Muebles,PDF Dic
32,Ocoyoacac,MUNICIPIO,M4,Conciliación Físico-Contable de Bienes Muebles,XLS Dic
33,Ocoyoacac,MUNICIPIO,M4,Actas del Comité y Anexos donde presenten los ...,PDF Dic
34,Ocoyoacac,MUNICIPIO,M4,Notas relacionadas con los Bienes Muebles e In...,PDF Dic

In [21]:
exportar_excel(archivos_incumplimiento_modulos_entidades(archivos,['M1','M2','M3','M4']),'archivos_incumplimiento_entidades_modulos')

/usr/local/lib/python3.7/dist-packages/openpyxl/worksheet/_reader.py:312: UserWarning: Data Validation extension is not supported and will be removed
  warn(msg)

#**4.Análisis Mensual**

**4.1 Análisis mensual por módulo**

In [22]:
archivo=archivos[1]
df=leer_limpiar(archivo)

/usr/local/lib/python3.7/dist-packages/openpyxl/worksheet/_reader.py:312: UserWarning: Data Validation extension is not supported and will be removed
  warn(msg)

In [23]:
#Ahora intentaremos obtener el analisis por modulo de cada mes 

def analisis_modulo(archivos,modulo):

  #Creamos nuestras columnas
  columnas_cM=['Entidad', 'Tipo', 'Módulo' , 'Total de no','Total de si', 'Pocentaje de incumplimiento', 'Pocentaje de cumplimiento']
  #definimos nuestra primer fila como vacia 
  my_data_cM = np.array([['','','','','','','' ]])

  for archivo in archivos:
    M=crear_modulo(archivo, modulo)

  #Vamos agregando cada fila con la informacion de cada modulo
    my_data_cM=np.append (my_data_cM, np.array([[nombre_entidad(archivo),
                         tipo_entidad(archivo), modulo,contar_no(M), contar_si(M), porcentaje_no(M),porcentaje_si(M) ]]), axis = 0)
  
  df_cM = pd.DataFrame(data=my_data_cM, columns=columnas_cM)
  df_cM= df_cM.drop([0],axis=0)
  
  return df_cM

In [24]:
analisis_modulo(archivos,'M1_dic')

/usr/local/lib/python3.7/dist-packages/openpyxl/worksheet/_reader.py:312: UserWarning: Data Validation extension is not supported and will be removed
  warn(msg)

,Entidad,Tipo,Módulo,Total de no,Total de si,Pocentaje de incumplimiento,Pocentaje de cumplimiento
1,AlmoloyadeJuárez,DIF,M1_dic,19,31,38.0,62.0
2,Ocoyoacac,DIF,M1_dic,11,41,21.15,78.85
3,Ocoyoacac,MUNICIPIO,M1_dic,23,29,44.23,55.77

In [25]:
#Funcion que nos devuelve el analisis de todos los modulos de las entidades fiscalizables pos mes
def analisis_mensual_modulos(archivos, mes):
  if mes=='oct':
    modulos=['M1_oct','M2_oct','M3_oct','M4_oct']
    #Definimos la lista de los archivos de incumplimiento de cada archivo
    AM=[analisis_modulo(archivos,modulo) for modulo in modulos]
    #Concatenamos verticalmente en una sola dataframe
    vertical_stack = pd.concat(AM, axis=0)
    return vertical_stack
  if mes=='nov':
    modulos=['M1_nov','M2_nov','M3_nov','M4_nov']
    #Definimos la lista de los archivos de incumplimiento de cada archivo
    AM=[analisis_modulo(archivos,modulo) for modulo in modulos]
    #Concatenamos verticalmente en una sola dataframe
    vertical_stack = pd.concat(AM, axis=0)
    return vertical_stack
  if mes=='dic':
    modulos=['M1_dic','M2_dic','M3_dic','M4_dic']
    #Definimos la lista de los archivos de incumplimiento de cada archivo
    AM=[analisis_modulo(archivos,modulo) for modulo in modulos]
    #Concatenamos verticalmente en una sola dataframe
    vertical_stack = pd.concat(AM, axis=0)
    return vertical_stack

**4.2 Análisis mensual de los modulos de varias entidades fiscalizables**

In [26]:
analisis_mensual_modulos(archivos,'nov')

/usr/local/lib/python3.7/dist-packages/openpyxl/worksheet/_reader.py:312: UserWarning: Data Validation extension is not supported and will be removed
  warn(msg)
/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:24: RuntimeWarning: invalid value encountered in long_scalars
/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:21: RuntimeWarning: invalid value encountered in long_scalars

,Entidad,Tipo,Módulo,Total de no,Total de si,Pocentaje de incumplimiento,Pocentaje de cumplimiento
1,AlmoloyadeJuárez,DIF,M1_nov,12,27,30.77,69.23
2,Ocoyoacac,DIF,M1_nov,2,37,5.13,94.87
3,Ocoyoacac,MUNICIPIO,M1_nov,15,24,38.46,61.54
1,AlmoloyadeJuárez,DIF,M2_nov,0,12,0.0,100.0
2,Ocoyoacac,DIF,M2_nov,0,12,0.0,100.0
3,Ocoyoacac,MUNICIPIO,M2_nov,4,8,33.33,66.67
1,AlmoloyadeJuárez,DIF,M3_nov,0,0,nan,nan
2,Ocoyoacac,DIF,M3_nov,0,0,nan,nan
3,Ocoyoacac,MUNICIPIO,M3_nov,0,0,nan,nan
1,AlmoloyadeJuárez,DIF,M4_nov,12,1,92.31,7.69
2,Ocoyoacac,DIF,M4_nov,1,12,7.69,92.31
3,Ocoyoacac,MUNICIPIO,M4_nov,4,9,30.77,69.23

**4.3 Análisis general por mes de varias entidades**

In [39]:
def analisis_general_mes(archivos, mes):


  #Creamos nuestras columnas
  columnas_ct=['Entidad', 'Tipo', 'Mes','Total de no', 'Total de si', 'Pocentaje de incumplimiento mensual','Pocentaje de cumplimiento Mensual']
  #definimos nuestra primer fila como vacia 
  my_data_ct = np.array([['','','','','','','' ]])

  for archivo in archivos:
    df=leer_limpiar(archivo)
    #Creamos nuestros modulos

    if mes=='oct':
      M1=crear_M1_oct(df)
      M2=crear_M2_oct(df)
      M3=crear_M3_oct(df)
      M4=crear_M4_oct(df)

    if mes=='nov':
      M1=crear_M1_nov(df)
      M2=crear_M2_nov(df)
      M3=crear_M3_nov(df)
      M4=crear_M4_nov(df)
    if mes=='dic':
      M1=crear_M1_dic(df)
      M2=crear_M2_dic(df)
      M3=crear_M3_dic(df)
      M4=crear_M4_dic(df)

  
      #Definimos algunas variables que ocuparemos
    sis_trimestre=contar_si(M1)+contar_si(M2)+contar_si(M3)+contar_si(M4)
    nos_trimestre=contar_no(M1)+contar_no(M2)+contar_no(M3)+contar_no(M4)
    siyno_trimestre=sis_trimestre + nos_trimestre
    porcentaje_si_trimestre=round((sis_trimestre/(siyno_trimestre)*100),2)
    porcentaje_no_trimestre=round((nos_trimestre/(siyno_trimestre)*100),2)

    #Vamos agregando cada fila con la informacion de cada modulo
    my_data_ct=np.append (my_data_ct, np.array([[nombre_entidad(archivo),
                           tipo_entidad(archivo),mes, nos_trimestre, sis_trimestre, porcentaje_no_trimestre, porcentaje_si_trimestre]]), axis = 0)


  #Hacemos nuestro dataframe con tan informacion
  df_ct = pd.DataFrame(data=my_data_ct, columns=columnas_ct)
  df_ct= df_ct.drop([0],axis=0)
  return df_ct

In [40]:
analisis_general_mes(archivos,'nov')

/usr/local/lib/python3.7/dist-packages/openpyxl/worksheet/_reader.py:312: UserWarning: Data Validation extension is not supported and will be removed
  warn(msg)

,Entidad,Tipo,Mes,Total de no,Total de si,Pocentaje de incumplimiento mensual,Pocentaje de cumplimiento Mensual
1,AlmoloyadeJuárez,DIF,nov,24,40,37.5,62.5
2,Ocoyoacac,DIF,nov,3,61,4.69,95.31
3,Ocoyoacac,MUNICIPIO,nov,23,41,35.94,64.06

**4.3 Análisis general de todos los meses de varias entidades**

In [41]:
#Funcion que nos devuelve el analisis de todos los modulos de las entidades fiscalizables de todos los meses
def analisis_general_meses(archivos):
  AM=[analisis_general_mes(archivos,mes) for mes in ['oct','nov','dic']]
    #Concatenamos verticalmente en una sola dataframe
  vertical_stack = pd.concat(AM, axis=0)
  return vertical_stack

In [42]:
analisis_general_meses(archivos)

/usr/local/lib/python3.7/dist-packages/openpyxl/worksheet/_reader.py:312: UserWarning: Data Validation extension is not supported and will be removed
  warn(msg)

,Entidad,Tipo,Mes,Total de no,Total de si,Pocentaje de incumplimiento mensual,Pocentaje de cumplimiento Mensual
1,AlmoloyadeJuárez,DIF,oct,22,41,34.92,65.08
2,Ocoyoacac,DIF,oct,3,61,4.69,95.31
3,Ocoyoacac,MUNICIPIO,oct,23,41,35.94,64.06
1,AlmoloyadeJuárez,DIF,nov,24,40,37.5,62.5
2,Ocoyoacac,DIF,nov,3,61,4.69,95.31
3,Ocoyoacac,MUNICIPIO,nov,23,41,35.94,64.06
1,AlmoloyadeJuárez,DIF,dic,59,71,45.38,54.62
2,Ocoyoacac,DIF,dic,37,95,28.03,71.97
3,Ocoyoacac,MUNICIPIO,dic,64,65,49.61,50.39